### ISSUE TITLE
Policy Compliance Auditing

### ISSUE THREAD

**Issue by guandongershen** [elliot-bia/nessus#18]
Policy Compliance Auditing没有Compliance

**Comment by elliot-bia** [comment]
请附上截图 ，  复现步骤

**Comment by guandongershen** [comment]
> 请附上截图，复现步骤

![1](https://user-images.githubusercontent.com/44598912/195985076-eb500c95-fe53-40b1-a77d-ddfe734979de.png)
![2](https://user-images.githubusercontent.com/44598912/195985080-8211043f-8aa4-4a7f-9f0c-e57e7bec5c66.png)

我执行了以下两条命令
> docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus
> docker exec -it ramisec_nessus /bin/bash /nessus/update.sh

**Comment by elliot-bia** [comment]
**Describe the bug**
**描述问题**
A clear and concise description of what the bug is.
请用精炼的语言描述问题所在

**To Reproduce**
**问题浮复现**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

用以下步骤复现：
1，第一步。。。
2，第二步。。。
3，第三步。。。

**Expected behavior**
**期待行为**
A clear and concise description of what you expected to happen.
简要语言描述你期待这个程序想要响应的行为

**Screenshots**
**截图**
If applicable, add screenshots to help explain your problem.
务必带上截图

**Desktop (please complete the following information):**
**测试环境**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]


**Additional context**
**其他补充**
Add any other context about the problem here.

**Comment by elliot-bia** [comment]
我觉得应该是Nessus 版本问题，这个是SC版本

我平时用不上Policy Compliance Auditing， 所以并不了解Compliance

**Comment by guandongershen** [comment]
谢谢
