### ISSUE TITLE
cant restart nessus

### ISSUE THREAD

**Issue by xdon9** [elliot-bia/nessus#36]
Have you fixed the previous bug that couldn't be restarted？

**Comment by elliot-bia** [comment]
Not yet, busy work，I will solve it in weekend, maybe...

**Comment by lohodev** [comment]
@xdon9  you can just type 'sudo docker start nessus' on terminal as well as clear browser cookie. So, then you can start the Nessus on web app by entering 'https://localhost:8834'. @elliot-bia But the problem is I can't use scanning feature currently. 请快点更新 ！

![image](https://github.com/elliot-bia/nessus/assets/133323262/5a5476d3-177c-48d3-95ef-d92cc6913da4)

**Comment by elliot-bia** [comment]
> @xdon9 you can just type 'sudo docker start nessus' on terminal as well as clear browser cookie. So, then you can start the Nessus on web app by entering 'https://localhost:8834'. @elliot-bia But the problem is I can't use scanning feature currently. 请快点更新 ！
> 
> ![image](https://user-images.githubusercontent.com/133323262/246102511-5a5476d3-177c-48d3-95ef-d92cc6913da4.png)

copy that，do it right now
现在就搞，现在就搞，刚好今天空闲了下来😂😂

**Comment by elliot-bia** [comment]
bug fixed, please repull the images and run it again.
try 
```
docker pull ramisec/nessus
docker stop ramisec_nessus && docker rm ramisec_nessus
docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus
```
