### ISSUE TITLE
About Contributing

### ISSUE THREAD

**Issue by Sosiaka** [elliot-bia/nessus#48]
Hello!

I want to fork your project. The most important thing I would like to change is the download server. 
In some regions, the sources used in the project are blocked. For quick assembly and operation, I would like to get access to the project for further modification for these needs. 

The open source code will not be published. You can email me at sdkuygj.ghost@soaska.ru

**Comment by elliot-bia** [comment]
copy that, I will upload it later. I'm in holiday :)

**Comment by Sosiaka** [comment]
> copy that, I will upload it later. I'm in holiday :)

Just forked it.
Because of my methods, the image turned out to be 12 MB heavier than yours. I don't think it's critical.

**Comment by Sosiaka** [comment]
I'm not chasing the weight of images, but..


![img](https://hub.soaska.ru/apps/files_sharing/publicpreview/gENgGtnzFiaeDEp?file=/&fileId=11569&x=4800&y=2700&a=true&etag=f5b0103cf35e05fc08a2dfcac1df2a25)

**Comment by f3yc0w** [comment]
> copy that, I will upload it later. I'm in holiday :)

I would also like to fork this. I'm suddenly running into some form of anti-crack and if it turns out to not be something I can prevent through increased network isolation for the container, I will likely need to get my hands dirty. 

I'm more than happy to provide all details and solutions in the event that it becomes necessary to make changes!
